theme: jekyll-theme-hacker
title: (* Star Computer Shop/ Star Shop 
description: Merhaba Star* Teknoloji Hizmetinizde Hoşgeldiniz.Shop mağazını Lütfen tıklayın Uygun Fiyatlar!.Online Alışveriş Sitemiz Satışa başlamıştır çeşitlerimiz hazırlanmaktadır.Stripe güvencesiyle rahat bir alışveriş yapabilirsiniz.
yazar:  Erçetin Güler
