trtheme: jekyll-theme-hacker
title: (* Star Computer Net.tr/ Star Shop 
description: Merhaba Star* Teknoloji Hizmetinizde Hoşgeldiniz.Shop mağazını Lütfen tıklayın Uygun Fiyatlar!. 
Google Haritalar ve Github Sayfalarında Bulabilirsiniz. Bİze Ayırdığınız Vakit için Teşekkür ederiz.
online Alışveriş Sitemiz Satışa başlamıştır çeşitlerimiz hazırlanmaktadır.Stripe güvencesiyle rahat bir alışveriş yapabilirsiniz.
yazar:  Erçetin Güler
